### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by 2dragonly** [toommyliu/vexed#37]

**Comment by toommyliu** [comment]
The main reason I didn't bother with Windows support is that there are existing better alternatives [Skua](https://github.com/BrenoHenrike/Skua)/[Grimlite Li](https://github.com/Froztt13/Grimlite-Li) and would recommended using them over vexed. Have you tried them?

**Comment by 2dragonly** [comment]
Just want to try this.

**Comment by toommyliu** [comment]
https://github.com/toommyliu/vexed/releases/tag/0.0.4
